Revert "Pre-download debian:13 so tests work without Docker Hub access"
This reverts commit ca418129bc432bb38fde93e8f3200204ef8bdbc7.

Fails with this error:

------
 > [12/13] RUN skopeo copy docker://docker.io/library/debian:13 docker-archive:/preloaded-images/debian-13.tar:debian:13:
0.394 time="2026-02-13T23:06:48Z" level=fatal msg="initializing destination docker-archive:/preloaded-images/debian-13.tar:docker.io/library/debian:13: opening file \"/preloaded-images/debian-13.tar\": open /preloaded-images/debian-13.tar: no such file or directory"
------
Dockerfile:96
--------------------
  94 |
  95 |     # Pre-download test base image so tests don't depend on Docker Hub availability.
  96 | >>> RUN skopeo copy docker://docker.io/library/debian:13 docker-archive:/preloaded-images/debian-13.tar:debian:13
  97 |
  98 |     RUN printf '[Unit]\nAfter=docker.service\nRequires=docker.service\n\n[Service]\nType=oneshot\nExecStart=/usr/bin/docker load -i /preloaded-images/debian-13.tar\n\n[Install]\nWantedBy=multi-user.target\n' \
--------------------
ERROR: failed to solve: process "/bin/sh -c skopeo copy docker://docker.io/library/debian:13 docker-archive:/preloaded-images/debian-13.tar:debian:13" did not complete successfully: exit code: 1